services:
  api:
    build: .
    container_name: solarne-api
    ports:
      - "127.0.0.1:8081:8080"
    environment:
      # ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: ${DEFAULT_CONNECTION_STRING}
      JwtSettings__SecretKey: ${JWT_SECRET_KEY}
      JwtSettings__ExpirationTimeInMinutes: ${JWT_EXPIRATION_TIME_IN_MINUTES}
      AdminSettings__AdminEmail: ${ADMIN_EMAIL}
      AdminSettings__AdminPassword: ${ADMIN_PASSWORD}
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: solarne-api-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - solarne_api_pg_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"
    restart: unless-stopped

volumes:
  solarne_api_pg_data: